CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bicycles (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text,
    price numeric(10,2) NOT NULL,
    inventory integer NOT NULL,
    img_url text
);

CREATE TABLE carts (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cart_id integer NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    bicycle_id integer NOT NULL REFERENCES bicycles(id) ON DELETE CASCADE,
    quantity integer NOT NULL DEFAULT 1,
    UNIQUE (cart_id, bicycle_id)
);

CREATE TABLE orders (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES users(id),
    total_price numeric(10,2) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    bicycle_id integer NOT NULL REFERENCES bicycles(id),
    quantity integer NOT NULL,
    price_at_purchase numeric(10,2) NOT NULL
);

CREATE INDEX idx_carts_user_id ON carts(user_id);

CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX idx_cart_items_bicycle_id ON cart_items(bicycle_id);

CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);